<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VirtualGarage.VehicleSpecs.Domain.Services\VirtualGarage.VehicleSpecs.Domain.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="CarApi\Contracts\" />
    <Folder Include="CarApi\Mapping\" />
    <Folder Include="Interfaces\" />
  </ItemGroup>

</Project>
