<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>ca30ae1b-6cd9-4ec1-9435-cb5f243e54e5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Exceptions\" />
    <Folder Include="Interfaces\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VirtualGarage.Contracts\VirtualGarage.Api.Contracts.csproj" />
	  <ProjectReference Include="..\VirtualGarage.Persistence\VirtualGarage.Persistence.csproj" />
  </ItemGroup>

</Project>
